version: "3.9"
services:
  db:
    image: mysql:8.4.2
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: docker
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: rest_api
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306  # Mapeando a porta correta para o MySQL
    networks:
      - erudio-network

networks:
  erudio-network:
    driver: bridge