version: "3.9"
services:
  db:
    image: mysql:8.4.2
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: rest_api
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3309:3306
    networks:
      - rafa-network

  rest_api:
    build:
      context: './rest-with-springboot-and-java'
      dockerfile: Dockerfile
    container_name: rest_api_container
    depends_on:
      - db
    networks:
      - rafa-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rest_api?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    ports:
      - 8080:8080
    entrypoint: ["java", "-jar", "/app.jar"]

networks:
  rafa-network:
    driver: bridge
