spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_api
    username: postgres
    password: senha
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
    default-property-inclusion: NON_NULL

flyway:
  url: jdbc:postgresql://localhost:5432/
  schemas: rest_api
  user: postgres
  password: senha
