spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
    default-property-inclusion: NON_NULL

flyway:
  enabled: false
  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/
  schemas: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
